### PR TITLE
Replace FindBugs support with SpotBugs

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
@ArloL this is for https://github.com/m2e-code-quality/m2e-code-quality/issues/110 - OK for you?

**Comment by vorburger** [comment]
Wait, I'll amend this.. have JUST noticed that it doesn't update .fbExcludeFilterFile.. still some more findbugs-maven-plugin I overlooked to be replaced by spotbugs-maven-plugin ... :smile:

**Comment by vorburger** [comment]
@sewe just FYI

**Comment by vorburger** [comment]
@ArloL OK so this is the final version at least from my side now.. with the amendment, it actually works for real now; e.g. I've tested that the .fbExcludeFilterFile now gets created for SpotBugs instead of for FindBugs. Looking forward to your feedback and hoping that we can get this in!

**Comment by victornoel** [comment]
@ArloL any news on this?

**Comment by vorburger** [comment]
@victornoel FYI I'm planning to (self) merge this one, some time in the coming week or two - just want everything else to settle, first. It now occured to me that tecnically this is fairly major breaking change (it won't work with FindBugs anymore), which I guess is OK - focus on the future.

With 3/4 years hindsight, I now also see how I've changed "findbugs" to "spotbugs" here, but not actually renamed the folders themselves, so this could be slightly confusing for others in the future. I don't intend to sink more time into cleaning this up, but if you (or others reading this) want to follow-up on this PR and also rename `com.basistech.m2e.code.quality.findbugs` & Co. to be `com.basistech.m2e.code.quality.spotbugs`, in a new PR, then that could be sweet.

**Comment by victornoel** [comment]
@vorburger actually I was wondering if we shouldn't support both findbugs and spotbugs: we wouldn't touch the findbugs plugin and in the future continue work only on the spotbugs one.
I don't know if people are not still using findbugs: there is no need to make their life harder if it's not complex to do so...

**Comment by vorburger** [comment]
It would mean a lot of copy/paste - preferable?

My own motivation to redo this like that is somewhat limited, but if you
(or anyone else reading this) wants to offer a "friendly counter proposal"
to this PR in a new PR, basically applying what I have done here to a new
spotbugs plugin and feature that is "forked" from the findbugs one instead
of replacing it as proposed here, and it works, then I am totally fine to
merge that and abandon this.

Would some sort of timebox on this seem fair? Say not merging this for 2
(?) weeks, awaiting a possible alternative proposal?

Do others have thoughts about this? @arlol?

**Comment by erwint** [comment]
"friendly counter proposal" added as #136 ;)

**Comment by victornoel** [comment]
Nice work @erwint :)

**Comment by vorburger** [comment]
Abandon this in favour of #136 (which is based on and includes this work).

**Pull request closed without merging**
