### PR TITLE
FindBugs nature only for Java project

### PR DESCRIPTION
**Pull request by dojcsak**
Disable adding FindBugs nature when the project type is not Java.

### CODE REVIEW

**Comment by ArloL** [comment]
Thanks for the PR. Please continue sending PRs if you feel the need. Since we at work stopped using the plugin for performance reasons I can't tell whether everything works or not. So the community has to take over :/

**Comment by ArloL** [comment]
The develop build failed after merging. Could you have a look=

**Comment by adangel** [comment]
See #77 for the fix

**Comment by adangel** [comment]
rebased commit: 1830899b3da4d9cc15a44a3b244b7c9c8a331107

**Pull request merged**
