### PR TITLE
Store checkstyle-header and checktyle-suppressions files not under target/

### LINKED ISSUE #54: suppressionsLocation conflicting between maven and eclipse
The maven-checkstyle plugin puts the suppressions file in `${project.build.directory}` with the name `checkstyle-supressions.xml`. 

The m2e-code-quality plugin puts the suppressions file in the same directory, but it adds the execution id to the name, `checkstyle-suppressions-{executionId}.xml`.

When you launch a maven build outside of eclipse, the target directory is cleared, so the `checkstyle-suppressions-{executionId}.xml` gets deleted.

This then results in the following type of error in eclipse:
`Errors running builder 'Checkstyle Builder' on project 'xyz'.
cannot initialize module SuppressionFilter - Cannot set property 'file' in module SuppressionFilter to 'D:\projects\xyz\target\checkstyle-suppressions-default.xml': unable to find D:\projects\xyz\target\checkstyle-suppressions-default.xml`.

Doing a `Maven -> Update Project...` in eclipse creates the `checkstyle-suppressions-{executionId}.xml` again and thus solves the problem. But you have to do this after each maven build.

A possible solution could be to put the suppressions file in the eclipse `.settings` directory instead of the maven target directory.

### PR DESCRIPTION
**Pull request by adangel**
but rather under .metadata/.plugins/...
Fixes #54 and #71 - replaces pr #55

Basically the same like pr #55 , but just  against develop branch.

### CODE REVIEW

**Comment by ArloL** [comment]
Could you check what is up with Travis? I will merge then.

**Comment by adangel** [comment]
I've merged develop into my branch to get the latest fixes - it build now.

Please note, first merge https://github.com/m2e-code-quality/m2e-code-quality/pull/77 so that develop branch works again, then this PR should work too...

**Comment by sayresVT** [comment]
Any chance this PR is ready to be merged?

**Comment by adangel** [comment]
rebased commit: 75e0adeaffd38034826ecfefea21cd48f00b5623

**Pull request merged**
