### PR TITLE
bump Tycho from 0.24.0 to 1.2.0

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
@erwint @victornoel make sense, right - OK for you?

**Comment by erwint** [comment]
should be fine

**Comment by victornoel** [comment]
@vorburger I think so, I suppose you checked there weren't any breaking change that would surprise us later? :)

**Comment by erwint** [comment]
At least it builds. Currently I'm in the process of testing all my PRs together, I can switch tycho for this test, too.

**Comment by vorburger** [comment]
>  I suppose you checked there weren't any breaking change that would surprise us later? :)

nope, but it seems to build fine, and with the massive amount of tests this project has, I'm sure it's all good... :smile: (If it does break something, hopefully someone will scream and open a new issue and we'll have to see, or could revert this.)

**Pull request merged**
