### PR TITLE
[spotbugs] Add in 'verify' as a valid goal

### PR DESCRIPTION
**Pull request by hazendaz**
'verify' goal was added to maven project a long time ago.  I don't see any tests at all for spotbugs nor pmd, so I just aimed for getting the newer goal to be available here.

See https://github.com/search?q=repo%3Aspotbugs%2Fspotbugs-maven-plugin+%40Mojo&type=code

I didn't bother with 'gui' although that could be ran from Eclipse but typically would not.

Spotbugs verify mojo: https://spotbugs.github.io/spotbugs-maven-plugin/verify-mojo.html
Description of this goal, see https://github.com/spotbugs/spotbugs-maven-plugin/blob/master/src/main/groovy/org/codehaus/mojo/spotbugs/VerifyMojo.groovy

### CODE REVIEW

**Comment by hazendaz** [comment]
@adangel Any possibility this can get merged in?

**Review by adangel — APPROVED** [review]
Thanks!

**Comment by adangel** [comment]
I'll merge it as-is. However: "verify" only makes sense, if "spotbugs" goal has been executed before (or there is some other means of creating a spotbugs report that verify can use). So, maybe it is not really necessary? As you would have then in your pom.xml file both goals defined: "spotbugs" + "verify" instead of "check". And "spotbugs" is already covered.

By the way, the tests for Spotbugs are here:
- https://github.com/m2e-code-quality/m2e-code-quality/tree/develop/com.basistech.m2e.code.quality.spotbugs.test
- Sample projects for tests: https://github.com/m2e-code-quality/m2e-code-quality/tree/develop/com.basistech.m2e.code.quality.spotbugs.test/projects
- Test Class: https://github.com/m2e-code-quality/m2e-code-quality/blob/develop/com.basistech.m2e.code.quality.spotbugs.test/src/main/java/com/basistech/m2e/code/quality/spotbugs/tests/EclipseSpotbugsProjectConfigurationTest.java

Feel free to create another PR to add a sample project + unit test.

**Comment by hazendaz** [comment]
@adangel Good point!  I didn't think at this more than the new mojo was created.  You are correct, its created elsewhere (possibly in some other system) so it wouldn't really mean anything here other than known about.  Does this harm anything being present?

**Comment by adangel** [comment]
Ok, I've created now a test case, see #354. And it fails here:

https://github.com/m2e-code-quality/m2e-code-quality/blob/556a9a3f791b4833d49fa3e05384988fbdbdcca7/com.basistech.m2e.code.quality.spotbugs/src/main/java/com/basistech/m2e/code/quality/spotbugs/MavenPluginConfigurationTranslator.java#L290-L294

Obviously, we check here, that we only execute spotbugs once. Which makes sense.

As far as I understood the new verify goal, you _always_ have the spotbugs goal in your pom.xml. It's just executed in some earlier maven phase (in my test project, it's executed in prepare-package). If you don't use the spotbugs goal, then spotbugsXml.xml won't be created and the verify goal will never fail the build.

So, I'm going to revert your PR, as it is not needed.

**Comment by hazendaz** [comment]
@adangel Sorry for all the noise on this.  At least if any user comes along and is wondering why its not there they can find this history on the subject.

**Comment by hazendaz** [comment]
And thank you for taking time to test that out.  I appreciate going that extra mile even though it didn't end up needed and I could have saved face by not sending PR to start with :(  Anyway, hopefully this will answer any potential user questions down the road.

**Pull request merged**
