### PR TITLE
Just get a classloader for the Mojo, no need for an actual instance

### PR DESCRIPTION
**Pull request by erwint**
In big workspaces we noticed strange classloading errors in Eclipse, which result from Mojo instantiated for the ResourceResolver. As the Mojo instance is not needed at all (just it's classpath), we changed it to not actually create instances of the Mojo. Unfortunately, some internal m2e API is needed for this.

### CODE REVIEW

**Comment by vorburger** [comment]
> Unfortunately, some internal m2e API is needed for this.

@fbricon @mickaelistria perhaps you have any input into how (and whether) this can be avoided?

**Comment by mickaelistria** [comment]
Would `mojo.getClass().getClassloader()` return a classloader that could be used to get the classpath without requiring any m2e internal API?

**Comment by erwint** [comment]
no, there is no instance of the Mojo (that's the whole point)

**Comment by erwint** [comment]
The "only" internal API needed is `MavenImpl`, to access the public method `lookupComponent()`

**Comment by mickaelistria** [comment]
I think you should first refine "in big workspaces we noticed strange classloading errors in Eclipse" with something reproducible to narrow down the root cause. What you're suggesting seems more like a workaround IMO, and the real bug is that mojo instantation to screw up resource loading.
I'd strongly discourage relying on non-API, the risk of being broken often is very high. It could be even better to just duplicate code, and it would be best to join m2e project and try to make this a regular sustainable API first.

**Comment by erwint** [comment]
In an ideal world you might be right. But:

As I wrote, the problem is not reproducible, but a huge PITA. We get it mostly during startup in large workspaces. It might be a bug in m2e or in the way the Mojo was instantiated here, but in the end the instance is not even needed here at all. 

Honestly, turning to and waiting on m2e is no option: first of all, that would only work with they most recent version then. Also, our experience with getting someting into m2e is, eh, let's say "not ideal" (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=486737, which will soon have it's 3rd anniversary). 

Other m2e plugins are using `MavenImpl` too (e.g. m2e-wtp), so IMHO the risk is not _that_ high. Especially as there are bounds on the m2e version to use.

Also, I see no option to "duplicate code" here, as there is no other way to access the PlexusContainer that I can see.

**Comment by vorburger** [comment]
I don't want to get in the middle of something where there may be some prior history :smile_cat: but perhaps @erwint if you could at least open a new issue on M2E, and perhaps even raise a Gerrit there, with a proposal how to expose what API you would need to do this here "properly" to further discuss with @mickaelistria, more for the medium term, then perhaps for the short term this could already be merged here anyway?

**Comment by erwint** [comment]
I added https://bugs.eclipse.org/bugs/show_bug.cgi?id=539248 for m2e to provide an API

**Comment by erwint** [comment]
A gerrit change for m2e is now also provided: https://git.eclipse.org/r/#/c/129717/

**Comment by erwint** [comment]
Change in m2e has been merged, but will be available with 1.10 only. I suggest merging this PR and as soon as we require 1.10 (might be some while) to update it to the API in `IMaven`

**Comment by vorburger** [comment]
Agreed, and will do as soon as I'm not on mobile, walking around an
airport. - Or I really need to login to GitHub on this Mobile account so
that I can do it next time! ;)

**Pull request merged**
