### PR TITLE
Sanitize filenames derived from executionIds

### PR DESCRIPTION
**Pull request by erwint**
This is an alternative to #108

### CODE REVIEW

**Comment by vorburger** [comment]
In https://github.com/m2e-code-quality/m2e-code-quality/pull/108/commits/5ca085937caeca1d490cb2d188bfd5a90e94c506 you chopped off `"::"` where as here you went more general and seem to replace anything that is not `a-zA-Z0-9-_.` - LGTM!

**Comment by victornoel** [comment]
@erwint you forgot one there: https://github.com/m2e-code-quality/m2e-code-quality/blob/develop/com.basistech.m2e.code.quality.checkstyle/src/main/java/com/basistech/m2e/code/quality/checkstyle/EclipseCheckstyleProjectConfigurator.java#L150

**Comment by erwint** [comment]
I think that one's okay, is it is not used for a file name

**Comment by victornoel** [comment]
@erwint good, ok, I got confused by the name `createOrGetCheckstyleConfig` but it's not to create a file actually.

**Pull request merged**
