### PR TITLE
Redirect latest folder of the P2 repo to the new update site

### PR DESCRIPTION
**Pull request by antoine-morvan**
The content of the 'latest' folder of the repository was already duplicated in the folder '1.0.0.201705301746'.

The 'latest' repository will now points to the new repo at https://m2e-code-quality.github.io/m2e-code-quality-p2-site/

The URL http://m2e-code-quality.github.io/m2e-code-quality/site/ will continue to act as the aggregator update site (composite repo) that still references older versions (composite*.xml were already aggregating all the version folders) and reference the new repo via the updated 'latest' folder (that is addressing the issue  #143).

### CODE REVIEW

**Comment by antoine-morvan** [comment]
Well, https://antoine-morvan.github.io/m2e-code-quality/site/ and https://antoine-morvan.github.io/m2e-code-quality/site/latest/ are up for testing.

**Comment by erwint** [comment]
both p2 sites look good, but if we merge this AFAICT the latest "develop" version will immediately be available from both locations.

**Comment by antoine-morvan** [comment]
It's possible to setup sub repositories in the new site (latest / releases / snapshots), create a composite one that refer all of them, tune the redirections from the old one, etc. I think the architecture of the new update site is not clearly defined yet, so I can't do much about it for now...

**Comment by vorburger** [comment]
>  the latest "develop" version will immediately be available from both locations
> @vorburger : What is the strategy for releases regarding the update site?

My personal view is that for a project like this, simple CI/CD without ever actually cutting releases is just fine, and I thereore vote for this proposed change; and thank @antoine-morvan for putting it together! (See #123 : _"The last thing I have time for, for this project, is to do any sort of manual work for testing, or play Git Flow and merge a develop to master branch, to "cut releases" with "releases notes" and what not."_)

But I think its fair to first have a quick discussion thread here where anyone can chime in about this, so:

From an end-user point of view, for me, getting the latest and greatest whenever I do an update is great and just fine. And I accept that there is a chance that it could be broken, and that when people notice something broke and complain by raising issues, we can swiftly revert the PR which causes the problem, or find a fix. Personally I'm not running a bank in production with this (great!) Eclipse plugin. 

Now, people who use this project in an environment where they require more stability guarantess may disagree agree with this PoV, and would like to follow the more traditional release cycle. But that's work. Someone has to do that - ie. wake up and decide "well good morning, isn't it a great day to cut a release of m2e-code-quality today; let's see what changed since the last time we did this and write up some useful release notes". That won't be me... :smiley: But if anyone is, then please speak up here - the job of "release manager" for this project is yours to grab! :smiling_imp: As long as I can use https://m2e-code-quality.github.io/m2e-code-quality-p2-site/ to grab the latest and greatest, we can do with http://m2e-code-quality.github.io/m2e-code-quality/site/ what you all think would be best for the end-users of this project that are lurking out there. (@ArloL jump in [if anything to add, based on your experience](https://github.com/m2e-code-quality/m2e-code-quality/commits/gh-pages).)

One thing we could perhaps do is to bump the versions once, before we merge this, just to signal the "restart"? Again without any intention, at least from me, to then keep regularly raising versions and releasing after that. (BTW: That new bleeding edge https://m2e-code-quality.github.io/m2e-code-quality-p2-site/ actually just overwrites, and looses, the previous content, after each rebuild following any commits to master; nothing is preserved.)

> Is it supposed to be put manually somewhere?

If you are asking about the actual "mechanics" of how somehow who wanted to would have to "make 
a release", then yes [I guess the idea is to](https://github.com/m2e-code-quality/m2e-code-quality/blob/develop/doc/release.md) (manually) take the content of ...site/target/site and put it on https://github.com/m2e-code-quality/m2e-code-quality/tree/gh-pages/site ... 

And I guess also edit the compositeContent.xml and/or compositeArtifacts.xml (again manually, presumably; @antoine-morvan probably knows more about this).

**Comment by erwint** [comment]
I would greatly prefer to have something akin to a stable release. I would be willing to cut those releases from time to time, i.e. increase the version, build, deploy to gh-pages and edit composite*.xmls. So I propose to redirect only "latest" to the new site, which then has the current development snapshot.

**Comment by vorburger** [comment]
@erwint OK sure that works for me! @antoine-morvan will you about this accordingly?

**Comment by antoine-morvan** [comment]
That would impact both the new and old site along with the release system. Quite the changes. I'll look at it when I find some time.

**Comment by antoine-morvan** [comment]
Hi, 

So, I made a bit of research regarding the Travis deployment to GitHub pages. I did not find any "elegant" way to have an incremental deployment. Indeed, Travis deploy provider for GitHub pages either force push on the same commit or force push a new commit for every release. This erases all previous versions.

The easiest solution would be to git clone the current P2 repository, integrate its content with the new version to deploy (using tycho-p2-extras-plugin, composite repositories, or similar tools), then release on GitHub pages using current provider. Not that difficult to do, but the release time will increase linearly with the number of releases as we will need to fetch all the previous releases every time (and push the new ones too). 

Any opinions/positions on this?

Also, I noticed an inconsistency in the current Travis file: it is not advised to use the maven install goal when caching the maven local repository. The reasons are:
  * ‘mvn install’ goal publishes the built binaries in the local maven repository. With the local maven repository being cached, this goes against the good practice of not caching the built binaries (see https://docs.travis-ci.com/user/caching/#things-not-to-cache);
  * ‘mvn install’ goal publishes current version of the software to the local maven repository. That means the software can have dependencies to one of its older versions and it would not raise failure during CI. 
Solution would be to simply call ‘mvn clean verify’ during Travis CI.

Best.

**Comment by erwint** [comment]
Yes, that's what my research braught up, too. I did not find a good solution to automatically integrate it, but it's easy enough manually in gh-pages/site (copy it and include the path in compositeContent/Artifacts), so that should be fine.

So the only change IMHO is to remove "latest" from gh-pages/site

About mvn install: You're probably right, verify should be enough. 

Erwin

Am Montag, Oktober 22, 2018 15:33 CEST, Antoine Morvan <notifications@github.com> schrieb:
 
Hi,
So, I made a bit of research regarding the Travis deployment to GitHub pages. I did not find any "elegant" way to have an incremental deployment. Indeed, Travis deploy provider for GitHub pages either force push on the same commit or force push a new commit for every release. This erases all previous versions.
The easiest solution would be to git clone the current P2 repository, integrate its content with the new version to deploy (using tycho-p2-extras-plugin, composite repositories, or similar tools), then release on GitHub pages using current provider. Not that difficult to do, but the release time will increase linearly with the number of releases as we will need to fetch all the previous releases every time (and push the new ones too).
Any opinions/positions on this?
Also, I noticed an inconsistency in the current Travis file: it is not advised to use the maven install goal when caching the maven local repository. The reasons are:
 * ‘mvn install’ goal publishes the built binaries in the local maven repository. With the local maven repository being cached, this goes against the good practice of not caching the built binaries (see https://docs.travis-ci.com/user/caching/#things-not-to-cache); * ‘mvn install’ goal publishes current version of the software to the local maven repository. That means the software can have dependencies to one of its older versions and it would not raise failure during CI.
Solution would be to simply call ‘mvn clean verify’ during Travis CI.
Best.

**Comment by antoine-morvan** [comment]
Why remove latest from gh-pages/site ?
With the incremental deployment, we can have a separate folder with snapshot releases on the new site.

**Comment by erwint** [comment]
how many sites are there supposed to be? And what is "latest"? 

As far as I understood it there are 2 sites: one with released artifacts (gh-pages/site) and one with the latest snapshot (https://m2e-code-quality.github.io/m2e-code-quality-p2-site/, redirected to from gh-pages/site/latest). Then of course you don't  want latest to be included in the released artifacts site (which is then still manually updated with new releases from time to time)

If however "latest" is supposed to be a new site for the newly released artifacts that you somehow manage to automate, then of course you're right and latest can be included in gh-pages/site

**Comment by antoine-morvan** [comment]
Well, it's not clear to me if the "old" gh-pages branch will still be updated. We could let it be and have latest point to the "stable" folder of the new site. Then have the snapshot releases published to "snapshot" folder of the new site.

**Comment by antoine-morvan** [comment]
I made a small script to do this integration : https://github.com/antoine-morvan/m2e-code-quality/blob/develop/tools/before_deploy.sh

Resulting site is here : https://github.com/antoine-morvan/m2e-code-quality-p2-site
or here to try with eclipse : 
 * stable : https://antoine-morvan.github.io/m2e-code-quality-p2-site/
 * snapshot : https://antoine-morvan.github.io/m2e-code-quality-p2-site/snapshot/

**Comment by erwint** [comment]
Looks okay to me (assuming some of the versions found there are fabricated ones for testing: 1.1.1, 9.8.7, ...)

**Comment by vorburger** [comment]
@erwint I'm having a little less time for this project right now - please feel free to merge if this is OK for you.

**Comment by erwint** [comment]
It seems to me it's not done yet. My comment was just in reference to the resulting repos which @antoine-morvan posted and which look fine. But it's not what is produced from the current state of this PR

**Comment by ArloL** [comment]
It was once planned (predates my time) to somehow move the eclipse update site to Maven Central (see https://github.com/m2e-code-quality/m2e-code-quality/blob/3a405fe7faa2c7963d1d7a1853376203a64b6803/doc/release.md).

The ideal situation would be if new pushes to master would generate a new update site somewhere for the last commit id. Then one update site that contains all update sites (aka latest). This would allow users to always have the latest and greatest (Eclipse by default shows only the latest version in the install dialog), specify either a specific update site of the one version that works for them (at user's own risk so Eclipse won't automatically update), or use the catch all update site and use tools like oomph to possibly restrict the version (again at user's own risk).
This would also allow other eclipse plugin builds using tycho to reference a specific version of this plugin making their builds reproducible - a problem this project also has with the dependent plugins (checkstyle, etc.).

**Comment by erwint** [comment]
I added #175 which provides an aggregate site with releases + a separate snapshot site for the latest and greatest build straight off of develop. Thanks to @antoine-morvan for his great script! In this PR we would now just need to modify the text a bit to include the snapshot repository.

**Pull request merged**
